blank_lines_upper_bound = 2
combine_control_expr = false
comment_width = 100
force_multiline_blocks = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 100
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = false
reorder_impl_items = true
struct_lit_single_line = true
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
