[package]
name = "rust-vmaf"
version = "0.2.0"
edition = "2021"
authors.workspace = true
license.workspace = true
description = """
Safe bindings to the libvmaf.
"""

[lints]
workspace = true

[dependencies]
rust-vmaf-sys = { path = "../rust-vmaf-sys", version = "0.2" }
