[package]
name = "rust-vmaf-sys"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Sedlak <daniel@sedlak.dev>"]
license = "MIT"
description = """
Exported bindings for the libvmaf.
"""

[build-dependencies]
bindgen = { version = "0.69.4" }
