name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build

    - name: Clippy
      run: cargo clippy

    # TODO: Debug why it is not linking
    # - name: Tests with default features
    #   run: cargo test --verbose

    # - name: Tests with all features
    #   run: cargo test --features-all --verbose
